### ISSUE TITLE
Next and Finish button never called

### ISSUE THREAD

**Issue by ThomasVeitch** [ErrorxCode/ModernOnboarding#1]
Followed instructions.
Finish button (onNext) never gets called so you can never return to the Main Menu. Currently not fit for purpose. Shame, because the code design is quite elegant.

        OnBoarder.startOnBoarding(this, pages, new OnFinishLastPage() {
            @Override
            public void onNext() {

                Log.v("OnBoarding","startOnBoarding onNext called");
                OnBoardingActivity.this.startActivity(new Intent(OnBoardingActivity.this, MenuActivity.class));
            }
        });

**Comment by ErrorxCode** [comment]
Unfortunately, I am out of the development phase till April. If any one can contribute to fix this problem, it would be a great Favor for me (⁠•⁠‿⁠•⁠)

**Comment by ThomasVeitch** [comment]
To Fix, in activity_onboarding.xml, you need to put MaterialButton component, after ViewPager2 component. This will ensure it is at the top of the UI stack and pressable.

**Comment by ErrorxCode** [comment]
Please create a pull request with the fix, I will merge it as soon as
possible

**Comment by ErrorxCode** [comment]
> To Fix, in activity_onboarding.xml, you need to put MaterialButton component, after ViewPager2 component. This will ensure it is at the top of the UI stack and pressable.

They are inside **ConstraintLayout**. The order of views must not affect the arrangement and overlapping

**Comment by ErrorxCode** [comment]
I have checked. **onNext()** is working fine
